#!/bin/bash

FILEPATH=$1
FILENAME_W_EXTENSION=${FILEPATH##*/}
FILENAME=${FILENAME_W_EXTENSION%.*}
FILEDIR=${FILEPATH%/*.*}

EXEPATH=dist/build/llvm-compiler/llvm-compiler
LLVMAS=llvm-as

if [ -f $EXEPATH ]
then
  $EXEPATH $FILEPATH > $FILENAME.ll && $LLVMAS $FILENAME.ll -o $FILEDIR/$FILENAME.bc
else
  echo "Executable does not exist. Did you call 'make'?"
fi
